apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: caplin
  namespace: caplin
spec:
  selector:
    matchLabels:
      scrape-app: caplin
  endpoints:
  - port: metrics
    path: "/debug/metrics/prometheus"

